### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by kucherenko** [kiddkai/atom-node-debugger#10]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.161.0
**System**: linux 3.16.0-28-generic
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package, v0.2.3

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:126

TypeError: undefined is not a function
  at /home/apk/.atom/packages/node-debugger/lib/frame-view.coffee:42:22
  at _fulfilled (/opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:749:13)
  at /opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:810:14
  at flush (/opt/atom/resources/app/node_modules/pathwatcher/node_modules/q/q.js:108:17)
  at process._tickDomainCallback (node.js:409:11)

```

/cc @atom/core

**Comment by jchannon** [comment]
I get the same issue, open folder, chose debug project and get an error. I've tried various things but cant seem to get this package working :cry: any pointers?

**Comment by kiddkai** [comment]
Hey @jchannon, can you tell me which version of atom you are using?

Maybe update to the latest debugger & atom to check if this issue still exists?
