### ISSUE TITLE
Startup error "Cannot read property 'command' of undefined"

### ISSUE THREAD

**Issue by jackbrown** [kiddkai/atom-node-debugger#123]
1. Install node-resolver
2. Restart atom

Error appears on startup

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.2
**Thrown From**: [node-resolver](git://github.com/hughsk/atom-node-resolver) package, v1.0.1

### Stack Trace

Failed to activate the node-resolver package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.exports.activate (/Users/jackbrown/.atom/packages/node-resolver/index.js:12:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:500:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:483:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "fold-lines",
      "google-search",
      "overscroll"
    ],
    "projectHome": "/Users/jackbrown/git",
    "themes": [
      "one-dark-ui",
      "slime"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
atom-chai-snippets, v0.3.0
color-picker, v2.1.1
docblockr, v0.7.3
emmet, v2.4.1
file-icons, v1.6.14
foldername-tabs, v0.1.7
highlight-selected, v0.11.1
js-refactor, v0.6.0
jsonlint, v1.1.2
language-babel, v2.14.1
linter, v1.11.3
linter-eslint, v6.0.0
local-history, v3.2.3
markdown-preview, v0.157.1
node-resolver, v1.0.1
nvatom, v0.9.3
pigments, v0.22.1
project-manager, v2.7.5
refactor, v0.6.0
slime, v1.4.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by codecontemplator** [comment]
Hi,

Judging from the information this ptoblem seems to be in the node resolver package. Do you think this relates to the node debugger in some way?

**Comment by jackbrown** [comment]
d'oh i opened this ticket on the wrong package. sorry, feel free to delete.
