### ISSUE TITLE
Uncaught TypeError: Bad argument

### ISSUE THREAD

**Issue by qddegtya** [kiddkai/atom-node-debugger#14]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package, v0.2.3

### Stack Trace

Uncaught TypeError: Bad argument

```
At child_process.js:1134

TypeError: Bad argument
  at TypeError (native)
  at ChildProcess.spawn (child_process.js:1134:26)
  at exports.spawn (child_process.js:993:9)
  at /Users/archer/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/index.js:64:17
  at /Users/archer/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/node_modules/portscanner/lib/portscanner.js:144:7
  at Object.async.until (/Users/archer/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/node_modules/portscanner/node_modules/async/lib/async.js:584:13)
  at /Users/archer/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/node_modules/portscanner/node_modules/async/lib/async.js:580:23
  at /Users/archer/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/node_modules/portscanner/lib/portscanner.js:128:9
  at Socket.<anonymous> (/Users/archer/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/node_modules/portscanner/lib/portscanner.js:104:5)
  at Socket.emit (events.js:107:17)
  at TCP.close (net.js:461:12)

```

### Commands

```
     -2:28.7 snippets:next-tab-stop (input.hidden-input)
     -2:28.7 snippets:expand (input.hidden-input)
     -2:28.7 editor:indent (input.hidden-input)
  9x -2:28.1 core:backspace (input.hidden-input)
     -2:25.4 core:move-left (input.hidden-input)
 31x -2:15.4 core:backspace (input.hidden-input)
     -1:59.6 core:move-left (input.hidden-input)
  4x -1:52.7 core:save (input.hidden-input)
     -0:17.2 core:backspace (input.hidden-input)
 19x -0:16.5 core:save (input.hidden-input)
     -0:10.3 core:backspace (input.hidden-input)
 10x -0:09.9 core:save (input.hidden-input)
     -0:04.2 command-palette:toggle (input.hidden-input)
  7x -0:01.9 core:backspace (atom-text-editor.editor.mini)
     -0:00.1 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 node-debugger:toggle (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.2.6
emmet, v2.3.0
javascript-snippets, v1.0.0
jshint, v1.1.3
linter, v0.9.0
minimap, v3.4.9
monokai, v0.9.0
node-debugger, v0.2.3
travis-ci-status, v0.11.1
vim-mode, v0.22.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by tk3369** [comment]
Another one:

[Enter steps to reproduce below:]

Node path: /usr/local/bin/node
Application Path: /Users/tk3369/Development/javascript1/total.js

The sample code is here:
```
        function total(numbers) {
          var total = 0;
          for (var i = 0; i < numbers.length; i++) {
            total += numbers[i];
          }
          return total;
        }
        var numbers = [1,2,3,4,5,6,7,8,9,10];
        console.log("total of " + numbers + " is " + total(numbers));
```

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package, v0.2.3

### Stack Trace

Uncaught TypeError: Bad argument

```
At child_process.js:1134

TypeError: Bad argument
  at TypeError (native)
  at ChildProcess.spawn (child_process.js:1134:26)
  at exports.spawn (child_process.js:993:9)
  at /Users/tomkwong/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/index.js:64:17
  at /Users/tomkwong/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/node_modules/portscanner/lib/portscanner.js:144:7
  at Object.async.until (/Users/tomkwong/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/node_modules/portscanner/node_modules/async/lib/async.js:584:13)
  at /Users/tomkwong/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/node_modules/portscanner/node_modules/async/lib/async.js:580:23
  at /Users/tomkwong/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/node_modules/portscanner/lib/portscanner.js:128:9
  at Socket.<anonymous> (/Users/tomkwong/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/node_modules/portscanner/lib/portscanner.js:104:5)
  at Socket.emit (events.js:116:17)
  at TCP.close (net.js:477:12)

```

### Commands

```
     -1:29.7 core:select-up (atom-text-editor.editor)
     -1:23.5 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:59.9 core:move-up (atom-text-editor.editor)
  2x -0:59.0 core:move-left (atom-text-editor.editor)
     -0:58.3 core:move-down (atom-text-editor.editor)
  3x -0:49.3 core:select-up (atom-text-editor.editor)
  3x -0:46.6 core:move-down (atom-text-editor.editor)
  3x -0:46.1 core:move-up (atom-text-editor.editor)
     -0:10.9 node-debugger:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
node-debugger, v0.2.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by TylerBrock** [comment]
Bump

**Comment by tabman83** [comment]
Bump

**Comment by alexys95** [comment]
Bump

**Comment by slawo** [comment]
Bump

**Comment by kiddkai** [comment]
Sorry guys, I will wait atom upgrade to 1.0 to fix all the issues. I will keep looking at the update of atom, thanks for the bug reports :D

**Comment by panuhorsmalahti** [comment]
I got it too.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.1
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package, v0.2.3

### Stack Trace

Uncaught TypeError: Bad argument

```
At child_process.js:1119

TypeError: Bad argument
  at TypeError (native)
  at ChildProcess.spawn (child_process.js:1119:26)
  at exports.spawn (child_process.js:977:9)
  at /Users/nawi/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/index.js:64:17
  at /Users/nawi/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/node_modules/portscanner/lib/portscanner.js:144:7
  at Object.async.until (/Users/nawi/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/node_modules/portscanner/node_modules/async/lib/async.js:584:13)
  at /Users/nawi/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/node_modules/portscanner/node_modules/async/lib/async.js:580:23
  at /Users/nawi/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/node_modules/portscanner/lib/portscanner.js:128:9
  at Socket.<anonymous> (/Users/nawi/.atom/packages/node-debugger/node_modules/node-debugger/node_modules/debugger-runner/node_modules/portscanner/lib/portscanner.js:104:5)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at TCP.close (net.js:464:12)

```

### Commands

```
     -1:35.4.0 core:move-right (atom-text-editor.editor)
     -1:34.4.0 core:move-down (atom-text-editor.editor)
  2x -1:34.3.0 core:move-left (atom-text-editor.editor)
  2x -1:30.6.0 core:backspace (atom-text-editor.editor)
  2x -1:29.3.0 core:move-down (atom-text-editor.editor)
  2x -1:28.9.0 core:move-left (atom-text-editor.editor)
     -1:24.3.0 core:save (atom-text-editor.editor)
     -0:50.3.0 core:move-right (atom-text-editor.editor)
     -0:48.1.0 core:save (atom-text-editor.editor)
     -0:16.2.0 core:select-up (atom-text-editor.editor)
     -0:13.5.0 command-palette:toggle (atom-text-editor.editor)
     -0:12.4.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:12.4.0 core:cancel (atom-text-editor.editor.mini)
     -0:09.7.0 command-palette:toggle (atom-text-editor.editor)
     -0:08.3.0 core:confirm (atom-text-editor.editor.mini)
     -0:08.3.0 node-debugger:toggle (atom-text-editor.editor)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
node-debugger, v0.2.3

# Dev
No dev packages
```

**Comment by kiddkai** [comment]
Whole codebase have been upgraded. I shouldn't have this issue now.
