### ISSUE TITLE
Uncaught Error: Cannot find module './array-reverse.js'

### ISSUE THREAD

**Issue by adityamenon** [kiddkai/atom-node-debugger#150]
[Enter steps to reproduce below:]

1. Installed node-debugger package.
2. Opened up a .js file and hit F5 as instructed on the README.

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package, v1.4.4

### Stack Trace

Uncaught Error: Cannot find module './array-reverse.js'

```
At module.js:338

Error: Cannot find module './array-reverse.js'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at ArrayMethods (/Users/adityamenon/.atom/packages/node-debugger/node_modules/mercury/node_modules/observ-array/array-methods.js:30:19)
    at Object.ObservArray [as array] (/Users/adityamenon/.atom/packages/node-debugger/node_modules/mercury/node_modules/observ-array/index.js:76:12)
    at TreeView (/Users/adityamenon/.atom/packages/node-debugger/lib/Components/TreeView.coffee:19:17)
    at Object.builder.root (/Users/adityamenon/.atom/packages/node-debugger/lib/Components/BreakPointPane.coffee:41:16)
    at BreakpointPanel (/Users/adityamenon/.atom/packages/node-debugger/lib/Components/BreakPointPane.coffee:50:23)
    at App (/Users/adityamenon/.atom/packages/node-debugger/lib/Components/App.coffee:106:22)
    at Object.exports.start (/Users/adityamenon/.atom/packages/node-debugger/lib/Components/App.coffee:142:25)
    at Object.exports.show (/Users/adityamenon/.atom/packages/node-debugger/lib/node-debugger-view.coffee:15:11)
    at Debugger.start (/Users/adityamenon/.atom/packages/node-debugger/lib/debugger.coffee:290:24)
    at Debugger.start (/Users/adityamenon/.atom/packages/node-debugger/lib/debugger.coffee:1:1)
    at atom-workspace.module.exports.startOrResume (/Users/adityamenon/.atom/packages/node-debugger/lib/node-debugger.coffee:62:17)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:05.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:03.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:03.5.0 settings-view:open (atom-text-editor.editor)
     -0:51.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 node-debugger:start-resume (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter"
    ],
    "packagesWithKeymapsDisabled": [
      "jslint"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-light-syntax"
    ]
  },
  "node-debugger": {}
}
```

### Installed Packages

```coffee
# User
emmet, v2.4.1
go-plus, v3.5.4
node-debugger, v1.4.4

# Dev
No dev packages
```

**Comment by codecontemplator** [comment]
Hi,

It looks weird. Have you tried reinstalling the package?

**Comment by adityamenon** [comment]
I just tried reinstalling the package, this time it worked. The change in environment was me installing `node-inspector` package globally. I think I will be sticking to that package now though, because I find it really useful to get into Chrome's DevTools. Please feel free to close.

**Comment by Redsandro** [comment]
I had the same but it worked after restarting Atom.
