### ISSUE TITLE
Uncaught TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by ahmetcetin** [kiddkai/atom-node-debugger#151]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package, v1.4.4

### Stack Trace

Uncaught TypeError: Cannot read property 'config' of undefined

```
At /Users/ahmetcetin/.atom/packages/node-debugger/lib/debugger.coffee:288

TypeError: Cannot read property 'config' of undefined
  at Debugger.start (/Users/ahmetcetin/.atom/packages/node-debugger/lib/debugger.coffee:288:29)
  at Debugger.start (/Users/ahmetcetin/.atom/packages/node-debugger/lib/debugger.coffee:5:61)
  at atom-workspace.module.exports.startOrResume (/Users/ahmetcetin/.atom/packages/node-debugger/lib/node-debugger.coffee:62:17)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```

### Commands

```
     -4:53.3.0 core:copy (atom-text-editor.editor.mini.is-focused)
     -4:51.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -3:09.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:10.8.0 sort-lines:sort (atom-text-editor.editor.is-focused)
  2x -1:02.1.0 core:undo (atom-text-editor.editor.is-focused)
  5x -0:59.7.0 sort-lines:sort (atom-text-editor.editor.is-focused)
  8x -0:52.5.0 core:undo (atom-text-editor.editor.is-focused)
     -0:25.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  8x -0:21.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:15.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:12.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  3x -0:11.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:10.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10.8.0 node-debugger:start-resume (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "file-icons",
      "highlight-column"
    ],
    "packagesWithKeymapsDisabled": [
      "trailing-semicolon"
    ],
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ]
  },
  "node-debugger": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
angularjs, v0.3.4
atom-material-ui, v1.2.6
atom-ternjs, v0.13.2
auto-detect-indentation, v1.0.0
autoclose-html, v0.23.0
browser-plus, v0.0.54
color-picker, v2.1.1
docblockr, v0.7.3
editorconfig, v1.2.4
emmet, v2.4.2
emmet-snippets-compatibility, v1.0.4
haskell-grammar, v0.4.0
highlight-line, v0.11.1
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
language-babel, v2.15.6
language-ini, v1.14.0
language-javascript-semantic, v0.2.1
language-ocaml, v1.1.2
language-thrift, v1.0.2
linter, v1.11.3
linter-csslint, v1.3.2
linter-eslint, v7.1.1
linter-jscs, v3.4.8
linter-sass-lint, v1.1.2
linter-tidy, v2.1.0
minimap, v4.20.0
minimap-highlight-selected, v4.4.0
minimap-pigments, v0.2.0
node-debugger, v1.4.4
nuclide, v0.124.0
open-recent, v5.0.0
pigments, v0.24.5
preview-plus, v1.2.6
project-manager, v2.7.6
react, v0.14.1
rest-client, v0.5.1
rulerz, v0.4.1
save-session, v0.15.7
selection-highlight, v0.1.4
seti-icons, v0.4.5
smart-tags, v0.1.0
sort-lines, v0.14.0
tabs-to-spaces, v1.0.2
term3, v0.21.2
tool-bar, v0.3.0
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by codecontemplator** [comment]
Should be fixed now (in version 1.4.6).
