### ISSUE TITLE
Debugger can't find "required

### ISSUE THREAD

**Issue by dhoyt** [kiddkai/atom-node-debugger#156]

**Comment by codecontemplator** [comment]
Interesting. Do you get some error message or hint of what is going on?

**Comment by dhoyt** [comment]
Here is the stack trace ...

Error: Cannot find module 'globule'
at Function.Module._resolveFilename (module.js:339:15)
at Function.Module._load (module.js:290:25)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at Object.<anonymous> (C:\Dev\cur-workspace\curmusic-platform\curmusic-api\src\test\postman\regression\run_regressions\API_TEST.js:10:15)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.runMain [as _onTimeout] (module.js:447:10)
Connection attempt 1 to node process on 127.0.0.1:5858 failed. Will try again in 500.

**Comment by dhoyt** [comment]
Here are the first 3 lines of the program ....

var fs = require('fs');
var globule = require('globule');
var child_process = require('child_process');

It can find nodes 'fs' but gives up when trying to get/find 'globule' which is installed globally on my box 

>npm -g ls globule
C:\Users\Dick\AppData\Roaming\npm
`-- globule@0.2.0
