### ISSUE TITLE
Failed to load the node-debugger package

### ISSUE THREAD

**Issue by CrazySyntax** [kiddkai/atom-node-debugger#160]
Hi, 

I installed the files and put them under .atom/packages. When I opened atom I got the following error: 

> Cannot find module 'mercury'
> Hide Stack Trace
> Error: Cannot find module 'mercury'
>     at Module._resolveFilename (module.js:336:15)
>     at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
>     at Function.Module._load (module.js:286:25)
>     at Module.require (module.js:365:17)
>     at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
>     at Object.<anonymous> (/home/matan/.atom/packages/atom-node-debugger-1.4.7/lib/Components/App.coffee:1:6)
>     at Object.<anonymous> (/home/matan/.atom/packages/atom-node-debugger-1.4.7/lib/Components/App.coffee:1:1)
>     at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
>     at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
>     at Object.<anonymous> (/home/matan/.atom/packages/atom-node-debugger-1.4.7/lib/node-debugger-view.coffee:1:7)
>     at Object.<anonymous> (/home/matan/.atom/packages/atom-node-debugger-1.4.7/lib/node-debugger-view.coffee:1:1)
>     at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
>     at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
>     at Object.<anonymous> (/home/matan/.atom/packages/atom-node-debugger-1.4.7/lib/debugger.coffee:11:20)
>     at Object.<anonymous> (/home/matan/.atom/packages/atom-node-debugger-1.4.7/lib/debugger.coffee:1:1)
>     at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
>     at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
>     at Object.<anonymous> (/home/matan/.atom/packages/atom-node-debugger-1.4.7/lib/node-debugger.coffee:2:14)
>     at Object.<anonymous> (/home/matan/.atom/packages/atom-node-debugger-1.4.7/lib/node-debugger.coffee:1:1)
>     at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
>     at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
> 

Do you know how to resolve this problem?

**Comment by Sidon** [comment]
# npm install mercury

**Comment by codecontemplator** [comment]
I recommend using atom package manager to install packages for atom. npm install will probably solve your problem as well though.

**Comment by sudhirbitsgoa** [comment]
npm install also give this error

```
npm ERR! fetch failed https://registry.npmjs.org/tree-kill/-/tree-kill-0.1.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/geval/-/geval-2.1.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/ramda/-/ramda-0.14.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
npm ERR! fetch failed https://registry.npmjs.org/mercury/-/mercury-14.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 503
```

**Comment by codecontemplator** [comment]
@sudhirbitsgoa your problem seems to be npm related. https://github.com/npm/npm/issues/12960

**Comment by eimfach** [comment]
```
Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/robingruenke/.atom/packages/node-debugger/lib/debugger.coffee:5:12)
    at Object.<anonymous> (/Users/robingruenke/.atom/packages/node-debugger/lib/debugger.coffee:1:1)
    at Object.<anonymous> (/Users/robingruenke/.atom/packages/node-debugger/lib/debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/robingruenke/.atom/packages/node-debugger/lib/node-debugger.coffee:2:14)
    at Object.<anonymous> (/Users/robingruenke/.atom/packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Object.<anonymous> (/Users/robingruenke/.atom/packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:819:20)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:529:23)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:833:27)
    at <anonymous>
```

Atom: 1.28.2

**Comment by rsousacode** [comment]
[Enter steps to reproduce:]

1. ...
started app as /Applications/Atom/Contents/... /folder
2.failed installed pckg nodejs debugger?

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package 1.10.1


### Stack Trace

Failed to load the node-debugger package

```
At Cannot find module '_debugger'

Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/node-debugger/lib/debugger.coffee:5:12)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/node-debugger/lib/node-debugger.coffee:2:14)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:819:20)
    at PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:529:23)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:833:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
language-docker 1.1.8 
node-debugger 1.10.1 
```

**Comment by Alexkcreate** [comment]
I Think I should start over from scratch... I'm new. I like the idea of also using the nteract.io looks awesome. what do you guys think? if I start over do all npm installs

**Comment by Alexkcreate** [comment]
Like reinstall my linux os... no big deal. maybe try a different distro, or like debian or whatever. what do you recommend. I 've tried Ubuntu, Ubuntu bingee, Ubuntu mate, Mint cinimon, Fedora, xubuntu, lubuntu and that does it.  Prefered ubuntu mate, mint, and Fedora.  I could try a new one. Ideas?

**Comment by austincondiff** [comment]
I am getting this message as well upon installation... `Cannot find module '_debugger'`.

Does this package depend on any others being installed?

**Comment by Alexkcreate** [comment]
It might. I installed Atom and Electron. Atom is working just fine.
Electron doesn't have the right path. I think I just need to move it to my
home folder not sure. I didn't mean to send anything. I'm on Antergos.
Relative newbie, like to install packages until my system breaks. I should
use Vms or something. :)
Alex

**Comment by jaysaurus** [comment]
Investigating the stack trace for this issue points me to some asar files

**Comment by Alexkcreate** [comment]
okay, I'm using Debian now.. I had tried before but wasn't proficient
enough, not that it's hard, but i found it slight more. mayby their
partition map will make my system more stable than a super stable system.
it feels like a stable arch. WAY more software than the cononical ppl. It's
awesome for the software. they say it's fast.. id say it's normal. but I am
happy about it. it feels like the Manjaro or arch for developers because
you can get all the crazy free software! you could probably to it on the
others... if you can id love it if you passed that info on. otherwise i'll
check in on a forum.

**Comment by eimfach** [comment]
I guess this could be the problem:
package.json

  "engines": {
    "atom": ">0.200.0"
  }

Meaning this package is very much outdated and the current atom versions are using a much higher npm version ? As I remember since npm 5 or 6 there were breakibg changes regarding that all dependencies no matter how deep nestes were installed 'flat' into a directory ..

Could this be part of the issue here ?



Send from phone

**Comment by Alexkcreate** [comment]
I think That was it. I'm on Ubuntu Budgie. Seems much better. I'll check my
npm version. Thanks :)
Alex

**Comment by dionyziz** [comment]
This error occurs upon (atom, not npm-based) installation with the latest atom on the latest Ubuntu.

**Comment by Shawnxkwang** [comment]
This error occurs on atom 1.28.0 x64, when installing direct from atom "Install Packages"

**Comment by sanket-berde** [comment]
`Cannot find module '_debugger'`  This error occurs on atom 1.30.0 x64 Windows 10

**Comment by jetamartin** [comment]
Is this package still viable????
This issue was reported in 2016 (April 2nd) and still no fix!?
Maybe it's been abandoned?

**Comment by si458** [comment]
cannot find module '_debugger' atom 1.30.0 x64 OSX 10.13.6

**Comment by develax** [comment]
The same on Windows 10.

**Comment by a3s47k** [comment]
Anyone know how to fix it. Tks

**Comment by donutcake1** [comment]
_Problem still exists. I got this right after app installation & package adding._
-----------
App & OS version:
Atom: 1.30.0
OS: Windows 10 Home 1803 build 17134.285
----------
Tried to install these packages:
node-debugger
platformio-ide-terminal

**Comment by develax** [comment]
Guys, if you are under Windows, try to download Visual Studio Community Edition. While installing tick the checkbox of the "Node.js development" to add this component. There should be a good debugger for Node.

**Comment by codecontemplator** [comment]
As I understand i, the _debugger module has been removed from the node distribution. It has never been officially supported. It is a probably a significat amount of work to port to the new debug api. Also, I feel like mercury should also be replaced with something more actively maintained.

**Comment by jetamartin** [comment]
Ok Time to deep six this _debugger module...it's clearly not supported now.

**Comment by dylhack** [comment]
So what exactly is the solution for this error? I'm getting this issue
 - Fedora 28 XFCE spin
 - Atom 1.31.1
 - NPM 6.4.1
 - Node 8.12.0
 - Stack Trace: 
```
Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/devr2k/.atom/packages/node-debugger/lib/debugger.coffee:5:12)
    at Object.<anonymous> (/home/devr2k/.atom/packages/node-debugger/lib/debugger.coffee:1:1)
    at Object.<anonymous> (/home/devr2k/.atom/packages/node-debugger/lib/debugger.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/devr2k/.atom/packages/node-debugger/lib/node-debugger.coffee:2:14)
    at Object.<anonymous> (/home/devr2k/.atom/packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Object.<anonymous> (/home/devr2k/.atom/packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:782:33)
    at measure (/usr/share/atom/resources/app/src/package.js:143:22)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at Package.load (/usr/share/atom/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/src/package-manager.js:619:16)
    at PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:552:25)
    at PackageManager.atom.packages.loadPackage (/home/devr2k/.atom/packages/atom-ide-ui/modules/nuclide-commons-atom/FeatureLoader.js:527:32)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:690:23)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:267:15)
    at bufferStream (/usr/share/atom/resources/app/src/buffered-process.js:288:15)
    at Socket.stream.on (/usr/share/atom/resources/app/src/buffered-process.js:164:13)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

**Comment by janbrogger** [comment]
Issue is still present - CentOS 7.5, Atom 1.31.2, node 10.12.0.

**Comment by develax** [comment]
It seems they are not going to fix it soon. Download [VisualStudioCode](https://code.visualstudio.com/) and use it. It's available for Windows, macOS and Linux. It's free and debugger is great there. You can debug just inside the IDE itself or via Chrome browser.

**Comment by Morfiria** [comment]
Does this mean, I should use Visual Studio instead of Atom? I'm currently use it for react developing, but for some reasons I like to use Atom.

**Comment by develax** [comment]
You can debug Node.js using Chrome with or without Visual Studio.

**Comment by Morfiria** [comment]
Yes, I do this usually. Now I will uninstall the node-debugger package :-)

**Comment by JARVIS-AI** [comment]
Still have issue
macOS Mojave
Atom 1.32.0
Node 10.12.0

**Comment by develax** [comment]
They are not going to fix it.

**Comment by NewTony** [comment]
Still not work.

**Comment by padiazg** [comment]
For those looking to debug node.js from Atom, try using atom-ide with atom-ide-debugger-node
https://atom.io/packages/atom-ide-debugger-node

**Comment by bcorner13** [comment]
Remove the node-debugger package from your setup.  It doesn't look like its being maintained and is  not supported in the newer implementation of atom. As @padiazg suggested try the above packages.

**Comment by JARVIS-AI** [comment]
**Confirmed worked**
Thanks bro

**Comment by AntiViruskhan** [comment]
> For those looking to debug node.js from Atom, try using atom-ide with atom-ide-debugger-node
> https://atom.io/packages/atom-ide-debugger-node

thanks bro

**Comment by vaibhav3patil** [comment]
I have installed https://atom.io/packages/atom-ide-debugger-node but how can i run this, there is no documentation provide for that. Not able to run debugger.

**Comment by padiazg** [comment]
You should have now a "Debugger" menu, also in "View" menu there should be a "Toggle debugger" option.

Use "Launch debugger" to run your application with the --inspect option directly from Atom.

Use "Attach debugger" to attach to an instance you run by yourself, like a remote one.

Hope this helps you.

**Comment by kalarimonk** [comment]
Hi,
I recently installed the node debugger package through the atom ide and came up with the following issue:

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package 1.10.1


### Stack Trace

Failed to load the node-debugger package

```
At Cannot find module '_debugger'

Error: Cannot find module '_debugger'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/node-debugger/lib/debugger.coffee:5:12)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:146745)
    at /packages/node-debugger/lib/node-debugger.coffee:2:14)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:1:714332)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:3417381)
    at measure (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:3403921)
    at Package.measure (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:3402753)
    at Package.load (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:3403494)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:380859)
    at config.transact (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:379282)
    at Config.transact (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:331347)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:379220)
    at t.loadState.then (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:1:734943)
```

### Commands

```
```

### Non-Core Packages

```
node-debugger 1.10.1 
```


**Looks like this issue has been reported and closed but I still encountered it.** Any help in resolving this would be appreciated.

Thanks and Regards

**Comment by bampnet** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package 1.10.1


### Stack Trace

Failed to load the node-debugger package

```
At Cannot find module '_debugger'

Error: Cannot find module '_debugger'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/node-debugger/lib/debugger.coffee:5:12)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/node-debugger/lib/node-debugger.coffee:2:14)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:688212)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3220564)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3207104)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3205936)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3206677)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381128)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379856)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382428)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:940004
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:934610)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1128169)
    at e.bufferStream (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1128257)
    at Socket.e.on (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1126925)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)
```

### Commands

```
  2x -3:46.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -3:31.6.0 core:select-all (input.hidden-input)
  2x -3:31.2.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
compare-files 0.8.1 
node-debugger 1.10.1 
split-diff 1.6.0 
```

**Comment by LucianStoicescu** [comment]
+1 for this. It occurred for me on both Mac OS and windows when trying to install the node-debugger package. I even got the error when manually adding the package  (only tried on Mac OS)

**Comment by TheSHEEEP** [comment]
Another one:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.12
**OS**: "Manjaro Linux"
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package 1.10.1


### Stack Trace

Failed to load the node-debugger package

```
At Cannot find module '_debugger'

Error: Cannot find module '_debugger'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/usr/lib/electron4/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:336:28)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at /packages/node-debugger/lib/debugger.coffee:15:12)
    at /packages/node-debugger/lib/debugger.coffee:669:4)
    at /packages/node-debugger/lib/debugger.coffee:673:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at /packages/node-debugger/lib/node-debugger.coffee:6:14)
    at /packages/node-debugger/lib/node-debugger.coffee:184:4)
    at /packages/node-debugger/lib/node-debugger.coffee:188:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:121:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:255:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:68:27)
    at Package.requireMainModule (/usr/lib/atom/src/package.js:907:27)
    at measure (/usr/lib/atom/src/package.js:140:16)
    at Package.measure (/usr/lib/atom/src/package.js:81:19)
    at Package.load (/usr/lib/atom/src/package.js:126:10)
    at PackageManager.loadAvailablePackage (/usr/lib/atom/src/package-manager.js:711:10)
    at config.transact (/usr/lib/atom/src/package-manager.js:607:14)
    at Config.transact (/usr/lib/atom/src/config.js:892:14)
    at PackageManager.loadPackages (/usr/lib/atom/src/package-manager.js:605:17)
    at loadStatePromise.loadState.then (/usr/lib/atom/src/atom-environment.js:945:21)

```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-jinja2 0.6.0 
autoclose-html 0.23.0 
block-comment 0.4.3 
bracket-close-jump 0.2.0 
busy-signal 2.0.1 
copy-find-results 0.2.0 
docblockr 0.13.7 
escape-utils 0.5.3 
file-types 1.0.1 
fold-lines 0.2.2 
git-control 0.9.0 
git-plus 8.7.1 
haxe-import 1.2.1 
haxe-newfile 0.5.0 
indentation-indicator 1.1.0 
intentions 1.1.5 
language-batch 0.4.0 
language-bbcode 0.1.1 
language-brainfuck 0.2.0 
language-cmake 1.2.0 
language-doxygen 0.7.0 
language-haxe 0.6.0 
language-powershell 5.0.0 
language-vbscript 0.9.0 
last-cursor-position 0.9.3 
lime 0.3.5 
line-count 0.5.2 
linter 2.3.1 
linter-ui-default 1.8.1 
markdown-preview-plus 3.11.5 
markdown-writer 2.11.9 
node-debugger 1.10.1 
open-recent 5.0.0 
pretty-json 2.1.2 
python-debugger 0.2.0 
python-tools 0.6.9 
tabs-to-spaces 1.0.5 
tabular 0.1.0 
tidy-tabs 0.4.0 
```

**Comment by mastershaig** [comment]
same issue. Why the issue was closed without working solution ?

**Comment by Joeffreya** [comment]
same issue here :)

**Comment by Florian79** [comment]
same issue - who closed this issue?
