### ISSUE TITLE
Error serializing package 'node-debugger' TypeError: Cannot read property 'serialize' of null

### ISSUE THREAD

**Issue by nikmartin** [kiddkai/atom-node-debugger#165]
This error is continuously printed to the debug console in atom:
```
Error serializing package 'node-debugger' TypeError: Cannot read property 'serialize' of null
    at Object.module.exports.serialize (/home/nmartin/.atom/packages/node-debugger/lib/node-debugger.coffee:94:45)
    at Package.module.exports.Package.serialize (/usr/share/atom/resources/app.asar/src/package.js:619:100)
    at PackageManager.module.exports.PackageManager.serializePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:596:63)
    at PackageManager.module.exports.PackageManager.serialize (/usr/share/atom/resources/app.asar/src/package-manager.js:589:14)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/usr/share/atom/resources/app.asar/src/atom-environment.js:771:38)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:984:27

```
I'm running node-debugger 1.4.7 on atom 1.7.1

**Comment by npbenjohnson** [comment]
+1

**Comment by codecontemplator** [comment]
Should be fixed in the latest release
