### ISSUE TITLE
Uncaught TypeError: Cannot read property 'cleanup' of null

### ISSUE THREAD

**Issue by danielo515** [kiddkai/atom-node-debugger#178]
[Enter steps to reproduce below:]

1. Just tried to execute the current file using the direct shortcut. 
2. If it matters, I have a MacBook Pro and I have the function keys configured as actual function keys on single press( this means, no need to use `fn`key to hit `F5`)

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package, v1.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'cleanup' of null

```
At /Users/danielo/.atom/packages/node-debugger/lib/Components/App.coffee:156

TypeError: Cannot read property 'cleanup' of null
    at Object.exports.stop (/Users/danielo/.atom/packages/node-debugger/lib/Components/App.coffee:156:17)
    at Object.exports.destroy (/Users/danielo/.atom/packages/node-debugger/lib/node-debugger-view.coffee:22:7)
    at Debugger.cleanup (/Users/danielo/.atom/packages/node-debugger/lib/debugger.coffee:386:22)
    at Debugger.cleanup (/Users/danielo/.atom/packages/node-debugger/lib/debugger.coffee:1:1)
    at atom-workspace.module.exports.stop (/Users/danielo/.atom/packages/node-debugger/lib/node-debugger.coffee:84:15)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  3x -0:36.2.0 node-debugger:toggle-breakpoint (atom-text-editor.editor.is-focused)
     -0:21.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 18x -0:17.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.0 node-debugger:stop (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "node-debugger": {
    "nodePath": "/usr/local/bin/node"
  }
}
```

### Installed Packages

```coffee
# User
docblockr, v0.7.3
editorconfig, v1.4.1
git-control, v0.7.1
highlight-selected, v0.11.2
linter, v1.11.11
linter-eslint, v7.2.3
linter-markdown, v1.5.2
markdown-preview-plus, v2.4.0
minimap, v4.24.6
minimap-bookmarks, v0.3.1
minimap-codeglance, v0.4.5
minimap-cursorline, v0.2.0
minimap-git-diff, v4.3.1
minimap-hide, v0.3.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
node-debugger, v1.7.0

# Dev
No dev packages
```

**Comment by codecontemplator** [comment]
Does it happend all the time? Have you found any work arounds?

**Comment by danielo515** [comment]
I didn't found any workaround.

I'm not using atom anymore, I'm using VSCode now.

Regards
