### ISSUE TITLE
Uncaught Error: Cannot decorate a destroyed marker

### ISSUE THREAD

**Issue by antoniobusrod** [kiddkai/atom-node-debugger#194]
[Enter steps to reproduce below:]

1. Create sample Node.js script

```js
const a = 'foo';
console.log(a);
```

2. Set breakpoint in L2
3. Start debug
4. On breakpoint, close *atom-node-debugger*

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package, v1.7.0

### Stack Trace

Uncaught Error: Cannot decorate a destroyed marker

```
At /usr/share/atom/resources/app.asar/src/decoration-manager.js:192

Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/usr/share/atom/resources/app.asar/src/decoration-manager.js:192:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/usr/share/atom/resources/app.asar/src/text-editor.js:1540:37)
    at BreakpointManager.decorateBreakpoint (/home/toni/.atom/packages/node-debugger/lib/debugger.coffee:227:23)
    at Debugger.<anonymous> (/home/toni/.atom/packages/node-debugger/lib/debugger.coffee:143:14)
    at emitNone (events.js:85:20)
    at Debugger.emit (events.js:179:7)
    at Debugger.cleanupInternal (/home/toni/.atom/packages/node-debugger/lib/debugger.coffee:393:6)
    at Debugger.cleanupInternal (/home/toni/.atom/packages/node-debugger/lib/debugger.coffee:1:1)
    at Debugger.cleanup (/home/toni/.atom/packages/node-debugger/lib/debugger.coffee:387:6)
    at Debugger.cleanup (/home/toni/.atom/packages/node-debugger/lib/debugger.coffee:1:1)
    at cancel (/home/toni/.atom/packages/node-debugger/lib/Components/CancelButton.coffee:7:15)
    at Object.eventLambda (/home/toni/.atom/packages/node-debugger/node_modules/value-event/event.js:6:5)
    at Object.handleLambda (/home/toni/.atom/packages/node-debugger/node_modules/value-event/base-event.js:29:23)
    at Object.func (/home/toni/.atom/packages/node-debugger/node_modules/dom-delegator/dom-delegator.js:43:13)
    at /home/toni/.atom/packages/node-debugger/node_modules/dom-delegator/dom-delegator.js:172:36
    at Array.forEach (native)
    at callListeners (/home/toni/.atom/packages/node-debugger/node_modules/dom-delegator/dom-delegator.js:166:14)
    at findAndInvokeListeners (/home/toni/.atom/packages/node-debugger/node_modules/dom-delegator/dom-delegator.js:137:9)
    at HTMLHtmlElement.handler (/home/toni/.atom/packages/node-debugger/node_modules/dom-delegator/dom-delegator.js:127:9)
```

### Commands

```
     -0:23.9.0 node-debugger:toggle-breakpoint (atom-text-editor.editor.is-focused)
     -0:22.9.0 node-debugger:start-resume (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "emmet"
    ],
    "themes": [
      "one-light-ui",
      "solarized-dark-syntax"
    ]
  },
  "node-debugger": {
    "nodePath": "/usr/local/bin/node"
  }
}
```

### Installed Packages

```coffee
# User
atom-synth, v0.3.0 (inactive)
atom-ternjs, v0.15.0 (active)
csscomb, v0.3.1 (inactive)
editor-stats, v0.17.0 (active)
emmet, v2.4.3 (inactive)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
jshint, v1.8.6 (active)
linter, v1.11.16 (active)
linter-csslint, v1.3.2 (active)
node-debugger, v1.7.0 (active)
open-this, v0.2.0 (inactive)
sync-settings, v0.7.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (active)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (active)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by codecontemplator** [comment]
@antoniobusrod I fail to reproduce this. Does it happen all the time?

**Comment by antoniobusrod** [comment]
I have tried to reproduce the issue several times this morning unsuccessfully, so I'm closing the issue. Thank you for your attention.
