### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by eddwinpaz** [kiddkai/atom-node-debugger#24]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.179.0
**System**: Mac OS X 10.10.2
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package, v0.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/eddwinpaz/.atom/packages/node-debugger/lib/config-view.coffee:47

TypeError: Cannot read property 'getPath' of undefined
  at ConfigView.module.exports.ConfigView.autoFill (/Users/eddwinpaz/.atom/packages/node-debugger/lib/config-view.coffee:47:71)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:181:36)
  at HTMLButtonElement.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
  2x -32:48.5 core:select-all (atom-text-editor.editor.mini)
     -32:46.3 core:backspace (atom-text-editor.editor.mini)
     -32:43.7 core:confirm (atom-text-editor.editor.mini)
     -32:43.6 git-diff:toggle-diff-list (atom-text-editor.editor)
  9x -32:41.9 core:move-down (atom-text-editor.editor.mini)
     -32:40.1 editor:consolidate-selections (atom-text-editor.editor.mini)
     -32:40.1 core:cancel (atom-text-editor.editor.mini)
     -32:36.2 command-palette:toggle (atom-text-editor.editor)
     -32:31.2 core:confirm (atom-text-editor.editor.mini)
     -32:31.2 esformatter (atom-text-editor.editor)
     -32:29.5 core:save (atom-text-editor.editor)
     -31:55.8 node-debugger:toggle (atom-text-editor.editor)
     -31:36.4 core:paste (atom-text-editor.editor.mini)
     -30:39.2 core:copy (atom-text-editor.editor.mini)
     -30:38.2 core:paste (atom-text-editor.editor.mini)
     -30:25.9 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
esformatter, v1.3.0
indent-guide-improved, v1.1.1
jsonlint, v1.0.1
node-debugger, v0.2.3
pretty-json, v0.3.2

# Dev
No dev packages
```

**Comment by Trudko** [comment]
I've tried to debug (NodeJS Againts Humanity)[https://github.com/amirrajan/nodejs-against-humanity]

1. Git clone the project.
2. Run npm install.
3. Opened the project
4. Tried to run auto fill command

**Atom Version**: 0.186.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package, v0.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At C:\Users\Peter\.atom\packages\node-debugger\lib\config-view.coffee:47

TypeError: Cannot read property 'getPath' of undefined
  at ConfigView.module.exports.ConfigView.autoFill (C:\Users\Peter\.atom\packages\node-debugger\lib\config-view.coffee:47:71)
  at HTMLButtonElement.<anonymous> (C:\Users\Peter\AppData\Local\atom\app-0.186.0\resources\app\node_modules\space-pen\lib\space-pen.js:181:36)
  at HTMLButtonElement.handler (C:\Users\Peter\AppData\Local\atom\app-0.186.0\resources\app\src\space-pen-extensions.js:112:34)
  at HTMLButtonElement.jQuery.event.dispatch (C:\Users\Peter\AppData\Local\atom\app-0.186.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLButtonElement.elemData.handle (C:\Users\Peter\AppData\Local\atom\app-0.186.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)

```

### Commands

```
     -0:55.5 command-palette:toggle (atom-pane.pane.active)
     -0:54.2 core:confirm (atom-text-editor.editor.mini)
     -0:53.9 node-debugger:toggle (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-phpcs",
      "turbo-javascript",
      "jslint",
      "preview-plus",
      "linter-jshint",
      "jshint",
      "command-toolbar",
      "autocomplete"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.2.0
atom-grunt-configs, v0.1.0
atom-jshint, v1.5.0
coffee-compile, v0.11.0
grunt-runner, v0.7.0
js-refactor, v0.3.0
jsformat, v0.7.18
keybinding-cheatsheet, v0.0.8
linter, v0.12.0
linter-lsc, v1.1.2
linter-php, v0.0.11
linter-phpmd, v0.0.10
node-debugger, v0.2.3
notebook, v0.4.0
php-server, vundefined
phpunit, v1.0.9
phpunit-snippets, v0.1.0
refactor, v0.4.1
script, v2.18.0
script-runner, v1.7.1

# Dev
No dev packages
```

**Comment by jhopper28** [comment]
+1

**Comment by Apollon77** [comment]
WHy this is closed? I experienced it too in current version in Atom in a nodejs project ...
