### ISSUE TITLE
Cannot find module '_debugger' in Arch Linux Atom 1.24

### ISSUE THREAD

**Issue by upuldi** [kiddkai/atom-node-debugger#259]
**node version =  v9.8.0
uname -r = 4.15.7-1-ARCH**
**Atom Version = 1.24**

**Error Log :** 

Cannot find module '_debugger'
Hide Stack Trace
Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:485:15)
    at Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/lib/atom/src/module-cache.js:350:52)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/home/udoluweera/.atom/packages/node-debugger/lib/debugger.coffee:5:12)
    at Object.<anonymous> (/home/udoluweera/.atom/packages/node-debugger/lib/debugger.coffee:1:1)
    at Object.<anonymous> (/home/udoluweera/.atom/packages/node-debugger/lib/debugger.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/home/udoluweera/.atom/packages/node-debugger/lib/node-debugger.coffee:2:14)
    at Object.<anonymous> (/home/udoluweera/.atom/packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Object.<anonymous> (/home/udoluweera/.atom/packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Package.requireMainModule (/usr/lib/atom/src/package.js:777:27)
    at measure (/usr/lib/atom/src/package.js:138:16)
    at Package.measure (/usr/lib/atom/src/package.js:83:19)
    at Package.load (/usr/lib/atom/src/package.js:124:10)
    at PackageManager.loadAvailablePackage (/usr/lib/atom/src/package-manager.js:607:10)
    at config.transact (/usr/lib/atom/src/package-manager.js:520:14)
    at Config.module.exports.Config.transact (/usr/lib/atom/src/config.js:340:16)
    at PackageManager.loadPackages (/usr/lib/atom/src/package-manager.js:518:17)
    at loadStatePromise.loadState.then (/usr/lib/atom/src/atom-environment.js:804:21)
    at <anonymous>

**Comment by AbdelrahmanHafez** [comment]
I believe that may have to do with the fact that you're running node v9, which uses the inspector module instead. You can still run --inspector with chrome debugger, or switch to another text editor that supports the new inspector module natively, such as VSCode.

Currently, I don't think Atom supports running the inspector module with any package out there.

**Comment by TheBranchDriftCatalyst** [comment]
This is a pretty critical bug.  Is there any roadmap for a remedy.  Debuggers are a PITA to setup so I'd prefer to use the one, which from my estimates, is the most widely used.

**Comment by abilogos** [comment]
@AbdelrahmanHafez if you guide me a little, I guess I can work on it.
or can you provide me some links to what have been changed in the recent node versions?

**Comment by AbdelrahmanHafez** [comment]
@abilogos This comment was almost 4 years ago, I'm no longer using Atom, I'd recommend using the more supported VSCode.
Best of luck!
