### ISSUE TITLE
error

### ISSUE THREAD

**Issue by felipengeletrica** [kiddkai/atom-node-debugger#262]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Mac OS X 10.13.5
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package 1.10.1

### Stack Trace

Failed to activate the node-debugger package

```
At Cannot find module '_debugger'

Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/node-debugger/lib/debugger.coffee:5:12)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/node-debugger/lib/node-debugger.coffee:2:14)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:220:40)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:866:28)
```

### Commands

```
```

### Non-Core Packages

```
angularjs 0.5.3 
atom-html-preview 0.2.5 
autocomplete-clang 0.11.5 
browser-plus 0.0.98 
build 0.70.0 
busy-signal 1.4.3 
console-panel 0.3.0 
file-icons 2.1.22 
gpp-compiler 3.0.7 
ide-java 0.8.3 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
markdown-preview-plus 3.3.1 
node-debugger 1.10.1 
platformio-ide 2.1.7 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.8.3 
script 3.18.1 
tool-bar 1.1.7 
tree-view-git-status 1.5.0 
```

**Comment by jdolan** [comment]
I'm seeing this as well, same general setup (macOS High Sierra, latest Atom, Node 6.14.2).
