### ISSUE TITLE
Failed to activate the node-debugger package

### ISSUE THREAD

**Issue by Codjam** [kiddkai/atom-node-debugger#266]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.13.6
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package 1.10.1

### Stack Trace

Failed to activate the node-debugger package

```
At Cannot find module '_debugger'

Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom 5.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:154364)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:145671)
    at /packages/node-debugger/lib/debugger.coffee:5:12)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:146381)
    at Object.value [as .coffee] (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:145671)
    at /packages/node-debugger/lib/node-debugger.coffee:2:14)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:146381)
    at Object.value [as .coffee] (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:1:620607)
    at Package.requireMainModule (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:2964186)
    at Package.activateNow (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:2952320)
    at measure (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:2952098)
    at Package.measure (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:2949729)
    at activationPromise.activationPromise.Promise (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:2951958)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:2951901)
    at PackageManager.activatePackage (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:378471)
    at config.transactAsync (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:378087)
    at Config.transactAsync (/Applications/Atom 5.app/Contents/Resources/app/static/<embedded>:11:328274)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-nodejs-snippets 2.1.1 
atom-ternjs 0.18.3 
browser-plus 0.0.98 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
emmet 2.4.3 
intentions 1.1.5 
language-babel 2.85.0 
linter 2.2.0 
linter-ui-default 1.7.1 
node-debugger 1.10.1 
open-html-in-browser 0.2.1 
open-in-browser 0.5.2 
open-in-browsers 0.0.30 
pretty-json 2.0.3 
Quick-JavaScript 2.2.0 
script 3.18.1 
teletype 0.13.3 
```

**Comment by dhowe** [comment]
Same issue -- any feedback?

```
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Mac OS X 10.13.6
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package 1.10.1


### Stack Trace

Failed to activate the node-debugger package

At Cannot find module '_debugger'

Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at /packages/node-debugger/lib/debugger.coffee:5:12)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at /packages/node-debugger/lib/node-debugger.coffee:2:14)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:625254)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2961959)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2950093)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2949871)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2947502)
    at activationPromise.activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2949731)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2949674)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382481)
    at n.forEach.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:377715)
    at Array.forEach (<anonymous>)
    at disabledPackagesSubscription.disabledPackagesSubscription.config.onDidChange (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:377699)
    at emitter.on (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:335221)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190583)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1192024)
    at Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:337709)
    at Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:334949)
    at Config.set (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:330743)
    at Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:332766)
    at Package.enable (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2947287)
    at PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:375413)
    at HTMLButtonElement.enablementButtonClickHandler (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2934514)

### Commands


     -8:25.9.0 editor:select-to-end-of-line (input.hidden-input)
     -8:25.5.0 core:backspace (input.hidden-input)
     -8:24.9.0 editor:select-to-first-character-of-line (input.hidden-input)
  2x -8:24.6.0 core:backspace (input.hidden-input)
     -8:24.1.0 core:save (input.hidden-input)
     -8:23.6.0 core:undo (input.hidden-input)
     -8:22.8.0 core:backspace (input.hidden-input)
     -8:22.2.0 core:save (input.hidden-input)
     -8:14 editor:move-to-first-character-of-line (input.hidden-input)
  2x -8:12.9.0 core:save (input.hidden-input)
     -3:35.6.0 core:close (p.text.icon.icon-dashboard)
  3x -3:31.2.0 mocha-test-runner:run (input.hidden-input)
     -3:03.3.0 core:backspace (input.hidden-input)
     -3:02.8.0 core:save (input.hidden-input)
     -1:14.9.0 core:select-all (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:07.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)


### Non-Core Packages


atom-beautify 0.33.1 
atom-runner 2.7.1 
copy-as-rtf 0.9.3 
copy-with-style 1.1.0 
docblockr 0.13.7 
Extempore-Atom 0.3.2 
language-antlr 0.1.0 
merge-conflicts 1.4.5 
mocha-test-runner 1.0.0 
node-debug 0.1.7 
node-debugger 1.10.1 
term 0.2.4 


```

**Comment by yannicklarrivee** [comment]
[Enter steps to reproduce:]

1. ...Open Atom
2. ...

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.14.1
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package 1.10.1


### Stack Trace

Failed to activate the node-debugger package

```
At Cannot find module '_debugger'

Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:283:28)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (/app.asar/src/native-compile-cache.js:47:27)
    at /packages/node-debugger/lib/debugger.coffee:5:12)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:87:30)
    at /app.asar/src/compile-cache.js:235:23)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (/app.asar/src/native-compile-cache.js:47:27)
    at /packages/node-debugger/lib/node-debugger.coffee:2:14)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:87:30)
    at /app.asar/src/compile-cache.js:235:23)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (/app.asar/src/native-compile-cache.js:47:27)
    at Package.requireMainModule (/app.asar/src/package.js:776:27)
    at Package.activateNow (/app.asar/src/package.js:214:34)
    at measure (/app.asar/src/package.js:200:27)
    at Package.measure (/app.asar/src/package.js:82:19)
    at activationPromise.Promise (/app.asar/src/package.js:194:14)
    at new Promise (<anonymous>)
    at Package.activate (/app.asar/src/package.js:192:32)
    at PackageManager.activatePackage (/app.asar/src/package-manager.js:708:36)
    at config.transactAsync (/app.asar/src/package-manager.js:683:30)
    at Config.transactAsync (/app.asar/src/config.js:852:22)
    at PackageManager.activatePackages (/app.asar/src/package-manager.js:681:17)
    at PackageManager.activate (/app.asar/src/package-manager.js:660:44)
    at loadStatePromise.loadState.then (/app.asar/src/atom-environment.js:847:21)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-cform 0.6.0 
atom-cform-yaml 0.5.1-0 
atom-jade 0.3.0 
busy-signal 1.4.3 
editorconfig 2.2.2 
file-icons 2.1.26 
git-control 0.9.0 
git-plus 8.2.1 
git-time-machine 2.1.0 
go-plus 6.0.2 
highlight-selected 0.14.0 
intentions 1.1.5 
language-jade 0.7.3 
linter 2.2.0 
linter-eslint 8.4.1 
linter-js-cloudformation-yaml 2.2.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
mocha-test-runner 1.0.0 
node-debugger 1.10.1 
sync-settings 0.8.6 
```

**Comment by Michael-Downton** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.13.4
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package 1.10.1


### Stack Trace

Failed to activate the node-debugger package

```
At Cannot find module '_debugger'

Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:154368)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145675)
    at /packages/node-debugger/lib/debugger.coffee:5:12)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at /packages/node-debugger/lib/debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146385)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145675)
    at /packages/node-debugger/lib/node-debugger.coffee:2:14)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at /packages/node-debugger/lib/node-debugger.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146385)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:621455)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2967486)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2955620)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2955398)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2953029)
    at activationPromise.activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2955258)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2955201)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379950)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:379566)
    at Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:329753)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
auto-update-packages 1.0.1 
block-select 1.0.0 
box-edit 0.1.3 
busy-signal 2.0.0 
diff-pane 0.3.0 
file-icons 2.1.28 
git-blame 1.8.0 
intentions 1.1.5 
language-docker 1.1.8 
language-gherkin 1.0.4 
language-groovy 0.7.0 
language-ignore 1.7.4 
language-jenkinsfile 0.1.1 
language-markdown 0.29.0 
language-nginx 0.8.0 
linter 2.3.0 
linter-csslint 2.0.2 
linter-docker 0.3.2 
linter-eslint 8.5.0 
linter-markdown 5.2.2 
linter-ui-default 1.7.1 
markdown-toc 0.4.2 
node-debugger 1.10.1 
node-resolver 1.0.1 
open-recent 5.0.0 
pane-layout-plus 0.7.4 
pigments 0.40.2 
```

**Comment by briantully** [comment]
```apm uninstall node-debugger```

Alternatively:

```rm -fr /Applications/Atom.app```

```brew cask install visual-studio-code```

**Comment by hesske** [comment]
Same issue in 1.37.0 x64:
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows Server 2012 R2 Standard
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package 1.10.1


### Stack Trace

Failed to activate the node-debugger package

```
At Cannot find module '_debugger'

Error: Cannot find module '_debugger'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.37.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (<embedded>:11:154765)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (<embedded>:11:146072)
    at /packages/node-debugger/lib/debugger.coffee:15:12)
    at /packages/node-debugger/lib/debugger.coffee:669:4)
    at /packages/node-debugger/lib/debugger.coffee:673:3)
    at Module.get_Module._compile (<embedded>:11:146782)
    at Object.value [as .coffee] (<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (<embedded>:11:146072)
    at /packages/node-debugger/lib/node-debugger.coffee:6:14)
    at /packages/node-debugger/lib/node-debugger.coffee:184:4)
    at /packages/node-debugger/lib/node-debugger.coffee:188:3)
    at Module.get_Module._compile (<embedded>:11:146782)
    at Object.value [as .coffee] (<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (<embedded>:1:688410)
    at Package.requireMainModule (<embedded>:11:3550485)
    at Package.activateNow (<embedded>:11:3538619)
    at measure (<embedded>:11:3538397)
    at Package.measure (<embedded>:11:3536028)
    at activationPromise.activationPromise.Promise (<embedded>:11:3538257)
    at new Promise (<anonymous>:null:null)
    at Package.activate (<embedded>:11:3538200)
    at PackageManager.activatePackage (<embedded>:11:382562)
    at config.transactAsync (<embedded>:11:382178)
    at Config.transactAsync (<embedded>:11:332348)
    at PackageManager.activatePackages (<embedded>:11:382128)
    at PackageManager.activate (<embedded>:11:381746)
    at t.loadState.then (<embedded>:1:709967)
    at <anonymous>:null:null

```

### Commands

```
     -2:39.1.0 sync-settings:restore (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
     -2:18 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-prettify 0.1.3 
auto-id-class 0.7.1 
autoclose-html 0.23.0 
autocomplete-javascript 0.0.2 
autocomplete-json 5.5.2 
autocomplete-R 0.6.0 
autocomplete-sql 0.5.0 
busy-signal 1.4.3 
css-snippets 1.1.0 
css-spy 0.6.0 
es6-javascript 1.0.0 
eval-javascript 1.2.0 
flow-ide 1.11.0 
hey-pane 1.1.0 
highlight-selected 0.13.1 
html-to-css 0.2.2 
Hydrogen 2.4.1 
hyperclick 0.1.5 
ide-css 0.3.0 
ide-flowtype 0.23.0 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-flow 5.6.1 
linter-spell-javascript 0.9.0 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-plus 4.29.2 
node-debugger 1.10.1 
python-debugger 0.2.0 
Quick-JavaScript 2.2.0 
sync-settings 0.8.6 
```
