### ISSUE TITLE
Execution of invalid code in console causes crash

### ISSUE THREAD

**Issue by codecontemplator** [kiddkai/atom-node-debugger#52]
# Step to reproduce
1. Open a js file such as demo/a.js
2. Press F5 to start debugger 
3. Write some invalid code in the command window (under the console). Example: "abcde"

# Result
Uncaught TypeError: Cannot read property 'length' of undefined

# System and trace information
**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1
**Thrown From**: [node-debugger](https://github.com/kiddkai/atom-node-debugger) package, v1.1.4

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Daniel\.atom\packages\atom-node-debugger\node_modules\mercury\node_modules\main-loop\node_modules\raf\index.js:74

TypeError: Cannot read property 'length' of undefined
    at Grammar.module.exports.Grammar.tokenizeLine (C:\Users\Daniel\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\first-mate\lib\grammar.js:136:30)
    at tokenizeLine (/C:/Users/Daniel/.atom/packages/atom-node-debugger/lib/Components/ConsolePane.coffee:21:26)
    at Array.map (native)
    at Function.ConsolePane.render (/C:/Users/Daniel/.atom/packages/atom-node-debugger/lib/Components/ConsolePane.coffee:112:24)
    at LeftSidePane (/C:/Users/Daniel/.atom/packages/atom-node-debugger/lib/Components/App.coffee:33:21)
    at App.render (/C:/Users/Daniel/.atom/packages/atom-node-debugger/lib/Components/App.coffee:134:13)
    at redraw (C:\Users\Daniel\.atom\packages\atom-node-debugger\node_modules\mercury\node_modules\main-loop\index.js:62:23)
    at C:\Users\Daniel\.atom\packages\atom-node-debugger\node_modules\mercury\node_modules\main-loop\node_modules\raf\index.js:72:10
```

### Commands

```
  2x -1:48.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:47.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:47.3.0 core:move-up (atom-text-editor.editor.is-focused)
  9x -1:46.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:45.6.0 core:delete (atom-text-editor.editor.is-focused)
     -1:45.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:45 core:delete (atom-text-editor.editor.is-focused)
     -1:44.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:44.5.0 core:delete (atom-text-editor.editor.is-focused)
     -1:44.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:44 core:delete (atom-text-editor.editor.is-focused)
     -1:43.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:42.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:32.4.0 node-debugger:start-resume (atom-text-editor.editor.is-focused)
  5x -1:29.8.0 node-debugger:step-next (atom-text-editor.editor.is-focused)
  2x -1:07.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "node-debugger": {
    "nodePath": "C:/Apps/nodejs/node.exe"
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by kiddkai** [comment]
I will take a look tmr
